CREATE TABLE PROFESORES (
NOMBRECOMPLETO		VARCHAR2(60),
DNI					VARCHAR2(8) PRIMARY KEY NOT NULL,
DIRECCION			VARCHAR2(40),
TITULO				VARCHAR2(40),
GANA				NUMBER(6)
);

CREATE TABLE CURSOS (
NOMBRE_CURSO		VARCHAR2(30),
COD_CURSO			VARCHAR2(10) PRIMARY KEY NOT NULL,
DNI_PROFESOR		VARCHAR2(8) REFERENCES PROFESORES NOT NULL,
MAXIMO_ALUMNOS		NUMBER(2),
NUM_HORAS			NUMBER(4)
);

CREATE TABLE AULA (
NOMBRE				VARCHAR2(30),
COD_AULA			VARCHAR2(10) PRIMARY KEY NOT NULL,
COD_CURSO			VARCHAR2(10) REFERENCES CURSOS NOT NULL,
ESPACIO				NUMBER(3)
);

CREATE TABLE ALUMNOS (
NOMBRECOMPLETO		VARCHAR2(60) NOT NULL,
DNI 				VARCHAR2(8) PRIMARY KEY NOT NULL,
DIRECCION			VARCHAR2(40),
SEXO				VARCHAR2(1) CHECK (SEXO IN('H', 'M')) NOT NULL,
CURSO 				VARCHAR2(10) REFERENCES CURSOS NOT NULL
);

INSERT INTO PROFESORES VALUES ('Pedro Pepe Lopez', '32432455', 'LA DIRECCION 4', 'Informática', 7500);
INSERT INTO PROFESORES VALUES ('Laura Mellado', '43215643', 'SU CASA 32', 'Ingles', 5400);

INSERT INTO CURSOS VALUES ('Ingles', '1', '43215643', 20, 500);
INSERT INTO CURSOS VALUES ('Informatica', '2', '32432455', 25, 500);

INSERT INTO AULA VALUES ('Aula de ingles', '0', '1', 40);
INSERT INTO AULA VALUES ('Aula de informatica', '1', '2', 40);

INSERT INTO ALUMNOS VALUES ('alumnoDeAprobado', '12345678', 'Su Casa 10', 'H', '1');
INSERT INTO ALUMNOS VALUES ('alumnaDeSuspenso', '98765432', 'Su otra casa 10', 'M', '1');
INSERT INTO ALUMNOS VALUES ('alumnoQueEscribeEnComicSans', '18273645', 'No se sabe 5', 'H', '2');
INSERT INTO ALUMNOS VALUES ('alumnaQueNoViene', '10578275', 'Por ahi 100', 'M', '2');

UPDATE PROFESORES
	SET NOMBRECOMPLETO = 'Uvuvwevwevwe Onyetenyevwe Ugwemuhwem Osas'
	WHERE NOMBRECOMPLETO = 'Pedro Pepe Lopez';

DELETE FROM ALUMNOS
	WHERE DNI = '12345678';

ALTER TABLE ALUMNOS 
	ADD EDAD NUMBER(2);

SELECT NOMBRE_CURSO
FROM CURSOS
WHERE COD_CURSO ='1';

SELECT COUNT(DNI)
FROM ALUMNOS
WHERE CURSO ='2';

SELECT SUM(GANA)
FROM PROFESORES;